### PR TITLE
Buyer dash

### PR DESCRIPTION
**Pull request by JaeKralj**
\* **Checkist**

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Reference to issue (if any) 

* **what should reviewer look at ?

* **where is the main change at ?

* **Other information**:

reviwer: @jaekralj

### CODE REVIEW

**Comment by queen-techie** [comment]
please why did you delete the images in the assets folder and added it to the public folder

**Comment by queen-techie** [comment]
found this error on production 
image

kindly fix this

**Comment by queen-techie** [comment]
love this 


LGTM.

**Comment by queen-techie** [comment]
@JaeKralj kindly fix these

**Comment by JaeKralj** [comment]
Thanks, I'd look into it

**Comment by queen-techie** [comment]
no need you did not revert changes before pushing the PR template and the 404 page

so after merging the PR template branch these were automatically added 
please next time if you have an unmerged  PR and you are working on something else kindky checkout of that branch and revert changes before pushing

**Pull request closed without merging**
