### PR TITLE
Cart

### PR DESCRIPTION
**Pull request by JaeKralj**
\* **Checkist**

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Reference to issue (if any) 

* **what should reviewer look at ?

* **where is the main change at ?

* **Other information**:

reviwer: @jaekralj

### CODE REVIEW

**Comment by queen-techie** [comment]
please whats up with the countdown how do one now navigate to the login page

**Comment by JaeKralj** [comment]
Log in:
 I think someone removed the get started button, we'd need to add back to the navbar, maybe we add a log in button too

**Comment by JaeKralj** [comment]
> please whats up with the countdown how do one now navigate to the login page
> 
> 

countdown::
It's just a reminder to the first deadline of the project... Google's first deadline is March 17th (last time I checked), so I set it to March 15

**Comment by queen-techie** [comment]
please whats up with the countdown how do one now navigate to the login page



> Log in: I think someone removed the get started button, we'd need to add back to the navbar, maybe we add a log in button too

it seems it was my brother that removed it  i'll check to add it back but can you raise an issue on this and assign me  to this and also add a papercut label

**Pull request merged**
